
replicaCount: 2


image:
  pullSecrets: []
  repository: quay.io/kubocd/kcd-controller
  # -- Overrides the image tag whose default is the chart appVersion.
  tag:
  pullPolicy: IfNotPresent

# Allow to change some logger configuration
logger:
  mode: json
  level: info

metrics:
  enabled: false
  secured: false  # Set both TLS and client auth (see https://book.kubebuilder.io/reference/metrics)
  # This will be used to validate communication with the metrics endpoint
  # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
  certificateClusterIssuer:
  serviceMonitor:
    enabled: false
    name:  # -- Will default to {{ include "kubocd-controller.baseName" . }}
  # Following will allow a renaming of kubocd metrics related kubernetes resources
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-metrics
  serviceName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-metrics
  certificateName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-metrics
  secretName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-metrics
  certificateSelfSignedIssuerName:

webhook:
  enabled: true
  # This will be used to validate communication between the webhooks and the controllers.
  # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
  certificateClusterIssuer:
  # Following will allow a renaming of kubocd webhook related kubernetes resources
  # Leave it empty to use default values will works in most cases
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-webhook
  serviceName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-webhook
  certificateName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-webhook
  secretName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-webhook
  certificateSelfSignedIssuerName:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-validating-webhook-configuration
  validatingWebhookConfiguration:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-mutating-webhook-configuration
  mutatingWebhookConfiguration:

helmRepository:
  # -- Will default to {{ include "kubocd-controller.baseName" . }}-helm-repository
  serviceName:

networkPolicies:
  enabled: true
  fluxNamespace: flux-system


resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

volumeSize:
  works: 100Mi
  tmp: 100Mi

# Security Context for container
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

# -- Security Context for the whole pod
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# -- Annotations to be added to the pod
podAnnotations: {}

# -- Annotations to be added to all other resources
commonAnnotations: {}

# -- Hooks for specific configuration. Leave as is for standard usage
extraEnv:
additionalArgs: []
disableProbes: false
extraVolumes: []
#   - name:
#     mountPath:
#     claimName:




# Following will allow a renaming of all kubocd kubernetes resources
# Allow overriding base name of all resources
baseNameOverride:
# -- Will default to {{ include "kubocd-controller.baseName" . }}
deploymentName:
# -- Will default to {{ include "kubocd-controller.baseName" . }}
serviceAccountName:
# -- Will default to {{ include "kubocd-controller.baseName" . }}
clusterRoleName:

