#    Copyright 2025 Kubotal
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

APP_VERSION ?= v0.3.1-snapshot
DOCKER_TAG=${APP_VERSION}

REGISTRY ?= quay.io/kubocd
IMG ?= $(REGISTRY)/kubocd:${DOCKER_TAG}

HELM_VERSION ?= v0.3.1-snapshot

HELM_DOCKER_REPO := $(REGISTRY)/charts

# To authenticate for pushing in quay repo (img) (Use encrypted password):
# docker login quay.io

# To authenticate for pushing in quay repo (helm):
# helm registry login quay.io

# To authenticate for pushing in github repo:
# echo $GITHUB_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin


BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
#SHELL = /usr/bin/env bash -o pipefail
#.SHELLFLAGS = -ec

#.PHONY: all
#all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: version
version: ## Set version in binary
	@echo "// Generated by Makefile\n\npackage global\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/global/version_.go

.PHONY: manifests
manifests: ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

.PHONY: generate
generate: ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: verify-tool-versions
verify-tool-versions: ## Verify that .tool-versions and go.mod are in sync (MAJOR.MINOR comparison).
	@if [ -f .tool-versions ]; then \
		tool_go_full=$$(awk '/^golang/ {print $$2}' .tool-versions); \
		tool_go_minor=$$(echo "$$tool_go_full" | awk -F. '{print $$1"."$$2}'); \
		go_mod_minor=$$(grep -E '^go [0-9]+\.[0-9]+' go.mod | awk '{print $$2}' | awk -F. '{print $$1"."$$2}'); \
		if [ "$$tool_go_minor" != "$$go_mod_minor" ]; then \
			echo "ERROR: Go MAJOR.MINOR mismatch between .tool-versions and go.mod!"; \
			echo "  .tool-versions: golang $$tool_go_full (MAJOR.MINOR = $$tool_go_minor)"; \
			echo "  go.mod: go $$go_mod_minor"; \
			exit 1; \
		fi; \
		tool_k8s_full=$$(awk '/^kubectl/ {print $$2}' .tool-versions); \
		tool_k8s_minor=$$(echo "$$tool_k8s_full" | awk -F. '{print $$1"."$$2}'); \
		if [ "$$tool_k8s_minor" != "$(ENVTEST_K8S_VERSION)" ]; then \
			echo "ERROR: Kubernetes MAJOR.MINOR mismatch between .tool-versions and go.mod k8s.io/api!"; \
			echo "  .tool-versions: kubectl $$tool_k8s_full (MAJOR.MINOR = $$tool_k8s_minor)"; \
			echo "  go.mod (k8s.io/api -> ENVTEST_K8S_VERSION): $(ENVTEST_K8S_VERSION)"; \
			exit 1; \
		fi; \
		echo "Tool versions verified successfully: golang $$tool_go_full, kubectl $$tool_k8s_full"; \
	fi

.PHONY: verify-envtest-version
verify-envtest-version: verify-tool-versions ## Verify envtest version compatibility POSIX-compliantly.
	@if [ -n "$$KUBEBUILDER_ASSETS" ]; then \
		target="$$KUBEBUILDER_ASSETS"; \
		while [ -L "$$target" ]; do \
			target=$$(readlink "$$target"); \
		done; \
		dir_name=$$(basename "$$target"); \
		case "$$dir_name" in \
			$(ENVTEST_K8S_VERSION)*) \
				echo "Envtest version verified: $$dir_name matches expected $(ENVTEST_K8S_VERSION)*"; \
				;; \
			*) \
				echo "ERROR: Envtest version mismatch!"; \
				echo "  Active assets path: $$KUBEBUILDER_ASSETS (resolves to $$target)"; \
				echo "  Expected version prefix: $(ENVTEST_K8S_VERSION)* (derived from go.mod k8s.io/api)"; \
				exit 1; \
				;; \
		esac; \
	fi

.PHONY: check-tools
check-tools: ## Check if local tools match .tool-versions requirements.
	@echo "Checking local development tools against .tool-versions..."
	@failed=0; \
	if [ -f .tool-versions ]; then \
		go_req=$$(awk '/^golang/ {print $$2}' .tool-versions); \
		go_cur=$$(go version 2>/dev/null | awk '{print $$3}' | sed 's/go//' || true); \
		if [ -z "$$go_cur" ]; then echo "❌ Go is NOT installed! (Required: $$go_req)"; failed=1; \
		elif [ "$$go_req" != "$$go_cur" ]; then echo "❌ Go version mismatch! (Required: $$go_req, Installed: $$go_cur)"; failed=1; \
		else echo "✅ Go version matches ($$go_cur)"; fi; \
		\
		k8s_req=$$(awk '/^kubectl/ {print $$2}' .tool-versions); \
		k8s_cur=$$(kubectl version --client 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true); \
		if [ -z "$$k8s_cur" ]; then echo "❌ kubectl is NOT installed! (Required: $$k8s_req)"; failed=1; \
		elif [ "$$k8s_req" != "$$k8s_cur" ]; then echo "❌ kubectl version mismatch! (Required: $$k8s_req, Installed: $$k8s_cur)"; failed=1; \
		else echo "✅ kubectl version matches ($$k8s_cur)"; fi; \
		\
		helm_req=$$(awk '/^helm/ {print $$2}' .tool-versions); \
		helm_cur=$$(helm version --template='{{.Version}}' 2>/dev/null | sed 's/^v//' || true); \
		if [ -z "$$helm_cur" ]; then echo "❌ Helm is NOT installed! (Required: $$helm_req)"; failed=1; \
		elif [ "$$helm_req" != "$$helm_cur" ]; then echo "❌ Helm version mismatch! (Required: $$helm_req, Installed: $$helm_cur)"; failed=1; \
		else echo "✅ Helm version matches ($$helm_cur)"; fi; \
		\
		kind_req=$$(awk '/^kind/ {print $$2}' .tool-versions); \
		kind_cur=$$(kind version 2>/dev/null | awk '{print $$2}' | sed 's/^v//' || true); \
		if [ -z "$$kind_cur" ]; then echo "❌ Kind is NOT installed! (Required: $$kind_req)"; failed=1; \
		elif [ "$$kind_req" != "$$kind_cur" ]; then echo "❌ Kind version mismatch! (Required: $$kind_req, Installed: $$kind_cur)"; failed=1; \
		else echo "✅ Kind version matches ($$kind_cur)"; fi; \
		\
		flux_req=$$(awk '/^flux/ {print $$2}' .tool-versions); \
		flux_cur=$$(flux version --client 2>/dev/null | awk '/flux/ {print $$2}' | sed 's/^v//' || true); \
		if [ -z "$$flux_cur" ]; then echo "❌ Flux is NOT installed! (Required: $$flux_req)"; failed=1; \
		elif [ "$$flux_req" != "$$flux_cur" ]; then echo "❌ Flux version mismatch! (Required: $$flux_req, Installed: $$flux_cur)"; failed=1; \
		else echo "✅ Flux version matches ($$flux_cur)"; fi; \
	else \
		echo "❌ .tool-versions file not found!"; \
		failed=1; \
	fi; \
	exit $$failed

.PHONY: test
test: manifests generate fmt vet verify-envtest-version ## Run tests.
	@if [ -z "$$KUBEBUILDER_ASSETS" ]; then \
		$(MAKE) setup-envtest; \
		KUBEBUILDER_ASSETS="$$($(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path)" go test ./... -coverprofile cover.out; \
	else \
		KUBEBUILDER_ASSETS="$$KUBEBUILDER_ASSETS" go test ./... -coverprofile cover.out; \
	fi

.PHONY: lint
lint: ## Run golangci-lint linter
	$(GOLANGCI_LINT) run

.PHONY: lint-fix
lint-fix: ## Run golangci-lint linter and perform fixes
	$(GOLANGCI_LINT) run --fix

.PHONY: lint-config
lint-config: ## Verify golangci-lint linter configuration
	$(GOLANGCI_LINT) config verify

ifndef ignore-not-found
  ignore-not-found = false
endif

.PHONY: install
install: manifests ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	$(KUSTOMIZE) build config/crd | $(KUBECTL) apply -f -

.PHONY: uninstall
uninstall: manifests ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config. Call with ignore-not-found=true to ignore resource not found errors during deletion.
	$(KUSTOMIZE) build config/crd | $(KUBECTL) delete --ignore-not-found=$(ignore-not-found) -f -

HELM_REPO_ADV_ADDR ?= localhost:9090

.PHONY: run
run: manifests generate fmt vet ## Run a controller from your host.
	# Note: ENABLE_WEBHOOKS=false is required in local out-of-cluster mode because
	# the API server cannot reach webhooks hosted on the developer machine without tunnels.
	# We also pass default local values for MY_POD_NAMESPACE and helmRepoAdvAddr.
	export ENABLE_WEBHOOKS=false; export MY_POD_NAMESPACE=default; go run ./cmd/kubocd/main.go controller --helmRepoAdvAddr=$(HELM_REPO_ADV_ADDR)

.PHONY: dev-up
dev-up: ## Bring up local Kind cluster with OCI registry and bootstrap Flux
	@bash ./hack/kind-with-registry.sh

.PHONY: dev-down
dev-down: ## Tear down local Kind cluster and OCI registry
	@kind delete cluster --name kubocd || true
	@docker rm -f -v kubocd-registry || true

##@ Build

.PHONY: build
build:  manifests generate fmt vet build-kubocd version ## Build kubocd binaries with dependencies

.PHONY: build-kubocd
build-kubocd: ## Build kubocd binary.
	CGO_ENABLED=0 go build -o bin/kubocd cmd/kubocd/main.go


.PHONY: cli-release
cli-release:		## Upload a release of kubocd cli client
	goreleaser release --clean --skip validate


.PHONY: cli-build
cli-build:		## Build locally a release of kubocd cli client
	goreleaser build --clean --skip validate


.PHONY: docker
docker: version docker-build docker-push  ## Build controller docker image and push

# If you wish to build the manager image targeting other platforms you can use the --platform flag.
# (i.e. docker build --platform linux/arm64). However, you must enable docker buildKit for it.
# More info: https://docs.docker.com/develop/develop-images/build_enhancements/
.PHONY: docker-build
docker-build: version ## Build docker image with the manager.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push ${IMG}

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
# Note: Cross-platform buildx pushing does not natively support the local HTTP registry (localhost:5001)
# because the buildx container driver runs on an isolated network and requires TLS/trusted registry configs.
# Use standard docker-build (which runs on the host network daemon) for local development testing.

#PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: version ## Build and push docker image for the manager for cross-platform support
	# copy existing Dockerfile and insert --platform=${BUILDPLATFORM} into Dockerfile.cross, and preserve the original Dockerfile
	sed -e '1 s/\(^FROM\)/FROM --platform=\$$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
	- $(CONTAINER_TOOL) buildx create --name kubocd-builder
	$(CONTAINER_TOOL) buildx use kubocd-builder
	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile.cross .
	- $(CONTAINER_TOOL) buildx rm kubocd-builder
	rm Dockerfile.cross



.PHONY: build-installer
build-installer: manifests generate ## Generate a consolidated YAML with CRDs and deployment.
	mkdir -p dist
	cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}
	$(KUSTOMIZE) build config/default > config/_dist_/install.yaml

##@ Helm

.PHONY: crds
crds: manifests ## Generate crds file into helm chart
	$(KUSTOMIZE) build config/crd -o helm/kubocd-ctrl/crds/crds.yaml

define CHART_CTRL_YAML
# File generated by Makefile
apiVersion: v2
name: kubocd-ctrl
version: $(HELM_VERSION)
sources:
  - https://github.com/kubocd/kubocd
appVersion: $(APP_VERSION)
endef
export CHART_CTRL_YAML

.PHONY: chart-ctrl-yaml
chart-ctrl-yaml: ## Generate the helm/kubocd-ctrl/Chart.yaml
	echo "$$CHART_CTRL_YAML" >./helm/kubocd-ctrl/Chart.yaml

.PHONY: chart-ctrl
chart-ctrl: chart-ctrl-yaml crds ## Build and push controller helm chart
	cd ./helm && helm package -d ./../tmp kubocd-ctrl && helm push ./../tmp/kubocd-ctrl-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}


define CHART_WH_YAML
# File generated by Makefile
apiVersion: v2
name: kubocd-wh
version: $(HELM_VERSION)
sources:
  - https://github.com/kubocd/kubocd
appVersion: $(APP_VERSION)
endef
export CHART_WH_YAML

.PHONY: chart-wh-yaml
chart-wh-yaml: ## Generate the helm/kubocd-wh/Chart.yaml
	echo "$$CHART_WH_YAML" >./helm/kubocd-wh/Chart.yaml

.PHONY: chart-wh
chart-wh: chart-wh-yaml crds ## Build and push webhook helm chart
	cd ./helm && helm package -d ./../tmp kubocd-wh && helm push ./../tmp/kubocd-wh-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}

.PHONY: charts
charts: chart-ctrl chart-wh ## Build and push both charts

##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

## Tool Binaries
KUBECTL ?= kubectl
KUSTOMIZE ?= kustomize
CONTROLLER_GEN ?= go tool controller-gen
ENVTEST ?= $(LOCALBIN)/setup-envtest
GOLANGCI_LINT ?= go tool golangci-lint

## Tool Versions
# Note: Kustomize, Controller-gen, and Golangci-lint versions are pinned via the
# `tool` directive in go.mod and invoked through `go tool ...` — no separate
# version variables are needed here.
#
# setup-envtest is kept in $(LOCALBIN) as an exception: the only published tags
# of its submodule (v0.24.x) require Go 1.26, while this project pins Go 1.25 in
# .tool-versions. It is therefore installed dynamically on host demand (and
# pre-cached globally inside the Devcontainer).
#
#ENVTEST_VERSION is the version of controller-runtime release branch to fetch the envtest setup script (i.e. release-0.20)
ENVTEST_VERSION ?= $(shell go list -m -f "{{ .Version }}" sigs.k8s.io/controller-runtime | awk -F'[v.]' '{printf "release-%d.%d", $$2, $$3}')
#ENVTEST_K8S_VERSION is the version of Kubernetes to use for setting up ENVTEST binaries (i.e. 1.31)
ENVTEST_K8S_VERSION ?= $(shell go list -m -f "{{ .Version }}" k8s.io/api | awk -F'[v.]' '{printf "1.%d", $$3}')


.PHONY: setup-envtest
setup-envtest: envtest ## Download the binaries required for ENVTEST in the local bin directory.
	@echo "Setting up envtest binaries for Kubernetes version $(ENVTEST_K8S_VERSION)..."
	@$(ENVTEST) use $(ENVTEST_K8S_VERSION) --bin-dir $(LOCALBIN) -p path || { \
		echo "Error: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
		exit 1; \
	}

.PHONY: envtest
envtest: $(ENVTEST) ## Download setup-envtest locally if necessary.
$(ENVTEST): $(LOCALBIN)
	$(call go-install-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest,$(ENVTEST_VERSION))

# Note: Golangci-lint is managed natively via Go 1.25 tools in go.mod.
# No local bin install rules needed.

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f $(1) || true ;\
GOBIN=$(LOCALBIN) go install $${package} ;\
mv $(1) $(1)-$(3) ;\
} ;\
ln -sf $(1)-$(3) $(1)
endef
