# This rule is not used by the project kubocd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kubocd.kubotal.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubocd
    app.kubernetes.io/managed-by: kustomize
  name: kubocd-setting-viewer-role
rules:
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - settings/status
  verbs:
  - get
