---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - configs
  - contexts
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - configs/finalizers
  - contexts/finalizers
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - configs/status
  - contexts/status
  - releases/status
  verbs:
  - get
  - patch
  - update
