---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - clusterconnections
  - clustercontracts
  - configs
  - connections
  - contexts
  - contracts
  - releases
  - replications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - clusterconnections/finalizers
  - clustercontracts/finalizers
  - configs/finalizers
  - connections/finalizers
  - contexts/finalizers
  - contracts/finalizers
  - releases/finalizers
  - replications/finalizers
  verbs:
  - update
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - clusterconnections/status
  - clustercontracts/status
  - configs/status
  - connections/status
  - contexts/status
  - contracts/status
  - releases/status
  - replications/status
  verbs:
  - get
  - patch
  - update
