---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - releases
  - settings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - releases/finalizers
  - settings/finalizers
  verbs:
  - update
- apiGroups:
  - kubocd.kubotal.io
  resources:
  - releases/status
  - settings/status
  verbs:
  - get
  - patch
  - update
