---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Config
metadata:
  name: conf01
  namespace: {{ .Release.Namespace }}
spec:
  kuboAppRedirects:
{{- toYaml .Values.config.kuboAppRedirects | nindent 4 }}
  imageRedirects:
{{- toYaml .Values.config.imageRedirects | nindent 4 }}
  clusterRoles:
{{- toYaml .Values.config.clusterRoles | nindent 4 }}
  defaultContexts:
{{- toYaml .Values.config.defaultContexts | nindent 4 }}

