{{ range .Values.contexts }}
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Context
metadata:
  name: {{ required "name must be defined" .name }}
  namespace: {{ required "namespace must be defined" .namespace  }}
spec:
  {{- with .description }}
  description: {{ . }}
  {{- end }}
  {{- with .protected }}
  protected: {{ . }}
  {{- end }}
  {{- with .parents }}
  parents:
{{- toYaml . | nindent 4 }}
  {{- end }}
  context:
{{- toYaml .context | nindent 4 }}
{{ end }}