{{ if .Values.config.enabled }}
---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Config
metadata:
  name: conf01
  namespace: {{ .Release.Namespace }}
spec:
{{- toYaml .Values.config.content | nindent 2 }}
{{ end }}

