
{{ if .Values.controller.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubocd.controller.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubocd.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubocd.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubocd.controller.labels" . | nindent 8 }}
        {{- include "kubocd.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.deployInControlPlane }}
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      {{- else }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /kubocd
          args:
            - controller
            - --leaderElect={{ ne .Values.controller.replicaCount 1.0 }}
            - --healthProbeBindAddress=:8081
            - --rootDataFolder=/works
            - --helmRepoAdvAddr={{ include "kubocd.controller.helm-repository.serviceName" . }}.{{.Release.Namespace}}.svc
            - --helmRepoBindAddr=:9090
            - --logMode={{ .Values.controller.logger.mode}}
            - --logLevel={{ .Values.controller.logger.level}}
            {{- if .Values.controller.metrics.enabled }}
            - --metricsBindAddress=:8443
              {{- if .Values.controller.metrics.secured }}
            - --metricsSecure=true
            - --metricsCertPath=/tmp/k8s-metrics-server/metrics-certs
              {{- else }}
            - --metricsSecure=false
              {{- end }}
            {{- else }}
            - --metricsBindAddress=0
            {{- end }}
          {{-  range .Values.controller.additionalArgs }}
            - {{ . }}
          {{- end }}
          env:
          {{- with .Values.controller.extraEnv }}
            {{- toYaml . | nindent 4 }}
          {{- end }}
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if not .Values.controller.disableProbes }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          ports:
            - containerPort: 9090
              name: helm-repository
              protocol: TCP
          {{- with .Values.controller.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.controller.containerSecurityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.controller.metrics.enabled }}
            - mountPath: /tmp/k8s-metrics-server/metrics-certs
              name: metrics-certs
              readOnly: true
            {{- end }}
            - mountPath: /works
              name: works
            - mountPath: /tmp
              name: tmp
          {{- if .Values.controller.extraVolumes }}
          {{- range .Values.controller.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kubocd.controller.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if .Values.controller.metrics.enabled }}
        - name: metrics-certs
          secret:
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            optional: false
            secretName: {{ include "kubocd.controller.metrics.secretName" . }}
        {{- end }}
        - name: works
          emptyDir:
            sizeLimit: {{ .Values.controller.volumeSize.works }}
        - name: tmp
          emptyDir:
            sizeLimit: {{ .Values.controller.volumeSize.tmp }}
      {{- if .Values.controller.extraVolumes }}
      {{- range .Values.controller.extraVolumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
      {{- end }}
      {{- end }}
{{ end }}