{{ if .Values.controller.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubocd.controller.helm-repository.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubocd.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "kubocd.controller.selectorLabels" . | nindent 6 }}


{{ if .Values.controller.metrics.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubocd.controller.metrics.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubocd.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "kubocd.controller.selectorLabels" . | nindent 6 }}
{{ end }}

{{ end }}
